# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "My Site"
email: your-email@domain.com
# This *MUST* be defined. If content served from root path set to empty string *NOT* "/".
# baseurl: ""
url: ""
# Build settings
# If you install this theme as a ruby gem theme uncomment this line.
# theme: jekyll-bootstrap-structure
markdown: kramdown
plugins:
  - jekyll-feed
  - octopress-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - jekyll-bootstrap-structure.gemspec
  - README.md
  - LICENSE.txt
include:
  - node_modules
  - .nojekyll
defaults:
  # Use this to include optional structural components
  - scope:
      path: ""
      type: "pages"
    values:
      structure:
        aside: false
  - scope:
      path: "posts"
      type: "pages"
    values:
      structure:
        aside: true
      paginate:
        per_page: 10
  - scope:
      path: ""
      type: "posts"
    values:
      structure:
        aside: true
      pinned: 0
# See _data/social_sites_db.yml for list of support sites.
designer:
  name: sgpinkus
  url: https://github.io/sgpinkus/
google_analytics_id: UA-xxxxxxxx-x
# navbar links must be absolute
navbar:
  menu:
    Home: /
    Contact: /contact/
    About: /about/
    Posts: /posts/
  logo: /assets/brand-logo.png
  social:
    github: /
    gitlab: /
    stack-overflow: /
    twitter: /
